version: '3.8'
services:
    php:
      hostname: php
      container_name: php
      build: ./php
      volumes:
        - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
        - ./php/pdo_snowflake.ini:/usr/local/etc/php/conf.d/pdo_snowflake.ini:ro
        - ./php/apache-default.conf:/etc/apache2/sites-available/000-default.conf:ro
        - ../:/var/www/html
      ports:
        - "8080:80"
      user: ${UID_GID}
      dns:
        - 8.8.8.8
        - 8.8.4.4
        - 9.9.9.9
        - 1.1.1.1
      extra_hosts:
        - "host.docker.internal:host-gateway"
      environment:
        - PHP_IDE_CONFIG=serverName=127.0.0.1
